// Generated by scripts/build.js from src/. Do not edit this file directly.
(function() {
  const __modules = {
"./src/main.js": function(module, exports, require) {
const { Plugin, Setting } = require("obsidian");
const CanvasGraphController = require("./canvas-graph");
const {
  CANVAS_LINK_COLOR_PROPERTY,
  CANVAS_NODE_LABEL_PROPERTY,
  CANVAS_NODE_SHAPE_PROPERTY
} = require("./graph-properties");

const TARGET_DEPTH = 2;
const GRAPH_VIEW_TYPE = "graph";
const LOCAL_GRAPH_VIEW_TYPE = "localgraph";
const SEARCH_HIGHLIGHT_OPTION = "searchHighlightMode";
const SEARCH_HIGHLIGHT_COLOR_OPTION = "searchHighlightColor";
const SEARCH_HIGHLIGHT_TOGGLE_CLASS = "cluddlegraphs-search-highlight-toggle";
const SEARCH_HIGHLIGHT_COLOR_CLASS = "cluddlegraphs-search-highlight-color";
const SEARCH_HIGHLIGHT_COLOR_MARKER = "__cluddlegraphsSearchHit";
const SEARCH_HIGHLIGHT_DEFAULT_COLOR = "#ff2d55";
const LEGACY_SEARCH_HIGHLIGHT_SENTINEL = { a: 1, rgb: 0xff00ff };
const RESET_CONFIRM_BUTTON_CLASS = "cluddlegraphs-reset-confirm";
const RESET_CONFIRMING_CLASS = "cluddlegraphs-reset-confirming";
const RESET_CONFIRM_TIMEOUT_MS = 5000;
const GRAPH_NODE_CENTER = 100;
const GRAPH_NODE_RADIUS = 100;
const GRAPH_NODE_DIAMETER = GRAPH_NODE_RADIUS * 2;

module.exports = class CluddleGraphsPlugin extends Plugin {
  onload() {
    this.canvasGraph = new CanvasGraphController(this);
    this.pendingLeaves = new WeakSet();
    this.enginePatches = new WeakMap();
    this.rendererPatches = new WeakMap();
    this.nodePatches = new WeakMap();
    this.linkPatches = new WeakMap();
    this.filterControls = new WeakMap();
    this.displayControls = new WeakMap();
    this.resetButtonPatches = new WeakMap();

    const syncSoon = () => {
      window.setTimeout(() => this.syncGraphViews(), 0);
      window.setTimeout(() => this.syncGraphViews(), 250);
    };

    this.app.workspace.onLayoutReady(syncSoon);
    this.registerEvent(this.app.workspace.on("layout-change", syncSoon));
    this.registerEvent(this.app.workspace.on("active-leaf-change", syncSoon));
    this.canvasGraph.onload();
  }

  onunload() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      this.restoreGraphEngine(this.getGraphEngine(leaf?.view));
    });
  }

  syncGraphViews() {
    this.enforceLocalGraphDepth();
    this.app.workspace.iterateAllLeaves((leaf) => {
      const engine = this.getGraphEngine(leaf?.view);
      if (!engine) {
        return;
      }

      this.initializeSearchHighlightOptions(engine);
      this.canvasGraph.syncEngine(engine);
      this.addGraphPanelToggle(engine);
      this.addGraphDisplayColorPicker(engine);
      this.patchGraphResetButton(engine);
      this.patchGraphEngine(engine);
      this.syncRendererSearchHighlights(engine);
    });
  }

  enforceLocalGraphDepth() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      if (!leaf?.view || leaf.view.getViewType?.() !== LOCAL_GRAPH_VIEW_TYPE) {
        return;
      }

      const viewState = leaf.getViewState?.();
      if (!viewState?.state) {
        return;
      }

      const options = viewState.state.options ?? {};
      if (options.localJumps === TARGET_DEPTH || this.pendingLeaves.has(leaf)) {
        return;
      }

      const nextViewState = {
        ...viewState,
        state: {
          ...viewState.state,
          options: {
            ...options,
            localJumps: TARGET_DEPTH
          }
        }
      };

      this.pendingLeaves.add(leaf);
      Promise.resolve(leaf.setViewState(nextViewState))
        .catch((error) => console.error("Failed to set local graph depth", error))
        .finally(() => this.pendingLeaves.delete(leaf));
    });
  }

  addGraphPanelToggle(engine) {
    const filterOptions = engine.filterOptions;
    const childrenEl = filterOptions?.childrenEl;
    if (!childrenEl) {
      return;
    }

    const trackedControlEl = this.filterControls.get(engine)?.settingEl;
    if (trackedControlEl?.parentElement === childrenEl) {
      this.placeSearchHighlightToggle(childrenEl, trackedControlEl);
      return;
    }

    this.removeDetachedControl(childrenEl, SEARCH_HIGHLIGHT_TOGGLE_CLASS, trackedControlEl);

    const setting = new Setting(childrenEl)
      .setName("Highlight search matches")
      .setClass("mod-toggle")
      .setClass(SEARCH_HIGHLIGHT_TOGGLE_CLASS)
      .addToggle((toggle) => {
        toggle
          .setValue(this.isHighlightModeEnabled(engine))
          .onChange((enabled) => {
            this.setHighlightMode(engine, enabled);
          });

        filterOptions.optionListeners[SEARCH_HIGHLIGHT_OPTION] = (value) => {
          if (typeof value === "boolean") {
            engine.options[SEARCH_HIGHLIGHT_OPTION] = value;
            toggle.setValue(value);
            this.refreshGraphSearch(engine);
          }
          return this.isHighlightModeEnabled(engine);
        };
      });

    this.placeSearchHighlightToggle(childrenEl, setting.settingEl);
    this.filterControls.set(engine, setting);
  }

  placeSearchHighlightToggle(childrenEl, settingEl) {
    childrenEl.appendChild(settingEl);
  }

  addGraphDisplayColorPicker(engine) {
    const displayOptions = engine.displayOptions;
    const childrenEl = displayOptions?.childrenEl;
    if (!childrenEl) {
      return;
    }

    const trackedControlEl = this.displayControls.get(engine)?.settingEl;
    if (trackedControlEl?.parentElement === childrenEl) {
      return;
    }

    this.removeDetachedControl(childrenEl, SEARCH_HIGHLIGHT_COLOR_CLASS, trackedControlEl);

    const setting = new Setting(childrenEl)
      .setName("Highlighted hit nodes")
      .setClass(SEARCH_HIGHLIGHT_COLOR_CLASS)
      .addColorPicker((colorPicker) => {
        colorPicker
          .setValue(this.getSearchHighlightColorHex(engine))
          .onChange((value) => {
            this.setSearchHighlightColor(engine, value);
          });

        displayOptions.optionListeners[SEARCH_HIGHLIGHT_COLOR_OPTION] = (value) => {
          if (typeof value === "string") {
            const color = this.normalizeHexColor(value);
            if (color) {
              engine.options[SEARCH_HIGHLIGHT_COLOR_OPTION] = color;
              colorPicker.setValue(color);
              this.refreshGraphSearch(engine);
              engine.renderer?.changed?.();
            }
          }
          return this.getSearchHighlightColorHex(engine);
        };
      });

    childrenEl.insertBefore(setting.settingEl, childrenEl.firstChild);
    this.displayControls.set(engine, setting);
  }

  removeDetachedControl(childrenEl, controlClass, trackedEl) {
    for (const existingEl of childrenEl.querySelectorAll?.(`.${controlClass}`) ?? []) {
      if (existingEl !== trackedEl) {
        this.detachElement(existingEl);
      }
    }
  }

  patchGraphResetButton(engine) {
    if (this.resetButtonPatches.has(engine)) {
      return;
    }

    const resetButton = engine.controlsEl?.querySelector?.(".graph-controls-button.mod-reset");
    if (!resetButton) {
      return;
    }

    const state = {
      confirmButton: null,
      timeoutId: null
    };

    const clearConfirmation = () => {
      if (state.timeoutId !== null) {
        window.clearTimeout(state.timeoutId);
        state.timeoutId = null;
      }

      this.detachElement(state.confirmButton);
      state.confirmButton = null;
      resetButton.classList?.remove(RESET_CONFIRMING_CLASS);
    };

    const confirmReset = (event) => {
      event.preventDefault();
      event.stopPropagation();
      clearConfirmation();
      this.resetGraphOptions(engine);
    };

    const onResetClick = (event) => {
      event.preventDefault();
      event.stopImmediatePropagation();

      if (state.confirmButton) {
        return;
      }

      state.confirmButton = this.createResetConfirmButton(resetButton, confirmReset);
      resetButton.classList?.add(RESET_CONFIRMING_CLASS);
      state.timeoutId = window.setTimeout(clearConfirmation, RESET_CONFIRM_TIMEOUT_MS);
    };

    resetButton.addEventListener("click", onResetClick, true);
    this.resetButtonPatches.set(engine, { resetButton, onResetClick, clearConfirmation });
  }

  createResetConfirmButton(resetButton, onClick) {
    const doc = resetButton.ownerDocument ?? document;
    const button = doc.createElement("button");
    button.type = "button";
    button.textContent = "Are you sure?";
    button.classList.add(RESET_CONFIRM_BUTTON_CLASS, "mod-warning");
    button.setAttribute("aria-label", "Confirm graph reset");
    button.addEventListener("click", onClick);
    resetButton.parentElement?.insertBefore(button, resetButton.nextSibling);
    return button;
  }

  setHighlightMode(engine, enabled) {
    engine.options[SEARCH_HIGHLIGHT_OPTION] = enabled;
    engine.onOptionsChange?.();
    this.refreshGraphSearch(engine);
  }

  setSearchHighlightColor(engine, value) {
    const color = this.normalizeHexColor(value);
    if (!color) {
      return;
    }

    engine.options[SEARCH_HIGHLIGHT_COLOR_OPTION] = color;
    engine.onOptionsChange?.();
    this.refreshGraphSearch(engine);
    engine.renderer?.changed?.();
  }

  isHighlightModeEnabled(engine) {
    return engine.options?.[SEARCH_HIGHLIGHT_OPTION] === true;
  }

  initializeSearchHighlightOptions(engine) {
    const savedOptions = this.getSavedGraphOptions(engine);

    if (typeof engine.options?.[SEARCH_HIGHLIGHT_OPTION] !== "boolean") {
      engine.options[SEARCH_HIGHLIGHT_OPTION] = savedOptions?.[SEARCH_HIGHLIGHT_OPTION] === true;
    }

    const savedColor = this.normalizeHexColor(savedOptions?.[SEARCH_HIGHLIGHT_COLOR_OPTION]);
    const currentColor = this.normalizeHexColor(engine.options?.[SEARCH_HIGHLIGHT_COLOR_OPTION]);
    engine.options[SEARCH_HIGHLIGHT_COLOR_OPTION] = currentColor ?? savedColor ?? SEARCH_HIGHLIGHT_DEFAULT_COLOR;
  }

  getSavedGraphOptions(engine) {
    if (engine.view?.getViewType?.() === LOCAL_GRAPH_VIEW_TYPE) {
      return engine.view?.leaf?.getViewState?.()?.state?.options ?? engine.view?.getState?.()?.options;
    }
    return this.app.internalPlugins?.getPluginById?.("graph")?.instance?.options;
  }

  patchGraphEngine(engine) {
    if (this.enginePatches.has(engine)) {
      return;
    }

    const originalSetQuery = engine.setQuery;
    const originalRender = engine.render;
    if (typeof originalSetQuery !== "function" || typeof originalRender !== "function") {
      return;
    }

    const plugin = this;
    engine.setQuery = function(queries) {
      plugin.currentSearchHighlightEngine = plugin.isHighlightModeEnabled(this) ? this : null;
      try {
        return originalSetQuery.call(this, plugin.prepareQueriesForSearchHighlight(this, queries));
      } finally {
        plugin.currentSearchHighlightEngine = null;
        plugin.syncRendererSearchHighlights(this);
      }
    };

    engine.render = function(...args) {
      const result = originalRender.apply(this, args);
      plugin.syncRendererSearchHighlights(this);
      return result;
    };

    this.enginePatches.set(engine, { setQuery: originalSetQuery, render: originalRender });
    this.patchRenderer(engine.renderer);
  }

  restoreGraphEngine(engine) {
    if (!engine) {
      return;
    }

    const patch = this.enginePatches.get(engine);
    if (patch) {
      engine.setQuery = patch.setQuery;
      engine.render = patch.render;
      this.enginePatches.delete(engine);
    }

    this.restoreGraphResetButton(engine);
    this.canvasGraph.restoreEngine(engine);
    this.removeGraphPanelControls(engine);
    this.clearRendererSearchHighlights(engine.renderer);
    this.restoreRenderer(engine.renderer);
  }

  restoreGraphResetButton(engine) {
    const patch = this.resetButtonPatches.get(engine);
    if (!patch) {
      return;
    }

    patch.clearConfirmation();
    patch.resetButton.removeEventListener("click", patch.onResetClick, true);
    this.resetButtonPatches.delete(engine);
  }

  removeGraphPanelControls(engine) {
    const filterControl = this.filterControls.get(engine);
    if (filterControl) {
      this.detachElement(filterControl.settingEl);
      this.filterControls.delete(engine);
    }

    const displayControl = this.displayControls.get(engine);
    if (displayControl) {
      this.detachElement(displayControl.settingEl);
      this.displayControls.delete(engine);
    }

    delete engine.filterOptions?.optionListeners?.[SEARCH_HIGHLIGHT_OPTION];
    delete engine.displayOptions?.optionListeners?.[SEARCH_HIGHLIGHT_COLOR_OPTION];
  }

  detachElement(element) {
    if (typeof element?.detach === "function") {
      element.detach();
    } else {
      element?.remove?.();
    }
  }

  resetGraphOptions(engine) {
    engine.filterOptions?.setDefaultOptions?.();
    engine.colorGroupOptions?.setColorQueries?.([]);
    engine.displayOptions?.setDefaultOptions?.();
    engine.forceOptions?.setDefaultOptions?.();
    engine.onOptionsChange?.();
    this.enforceLocalGraphDepth();
  }

  prepareQueriesForSearchHighlight(engine, queries) {
    if (!this.isHighlightModeEnabled(engine) || !Array.isArray(queries)) {
      return queries;
    }

    return queries.map((query) => {
      if (!query || query.color) {
        return query;
      }

      return { ...query, color: this.createSearchHighlightColor(engine) };
    });
  }

  syncRendererSearchHighlights(engine) {
    const renderer = engine?.renderer;
    if (!renderer) {
      return;
    }

    this.patchRenderer(renderer);
    this.patchRendererElements(renderer);

    if (!this.isHighlightModeEnabled(engine)) {
      this.clearRendererSearchHighlights(renderer);
      return;
    }

    const search = engine.filterOptions?.search?.getValue?.() ?? "";
    if (!search) {
      this.clearRendererSearchHighlights(renderer);
      return;
    }

    const ids = this.getCurrentSearchMatchIds(engine);
    renderer.searchHighlightColor = this.createSearchHighlightColor(engine);
    renderer.searchHighlightNodeIds = ids;
    renderer.searchHighlightNodes = new Set(
      Array.from(ids)
        .map((id) => renderer.nodeLookup?.[id])
        .filter(Boolean)
    );
    renderer.changed?.();
  }

  getCurrentSearchMatchIds(engine) {
    const ids = new Set();
    const filter = engine.fileFilter ?? {};

    for (const [id, value] of Object.entries(filter)) {
      if (this.isSearchHighlightSentinel(value)) {
        ids.add(id);
      }
    }

    return ids;
  }

  isSearchHighlightSentinel(value) {
    return !!value
      && typeof value === "object"
      && (value[SEARCH_HIGHLIGHT_COLOR_MARKER] === true
        || (
          value.a === LEGACY_SEARCH_HIGHLIGHT_SENTINEL.a
          && value.rgb === LEGACY_SEARCH_HIGHLIGHT_SENTINEL.rgb
        ));
  }

  clearRendererSearchHighlights(renderer) {
    if (!renderer) {
      return;
    }

    if (renderer.searchHighlightNodeIds?.size || renderer.searchHighlightNodes?.size || renderer.searchHighlightColor) {
      renderer.searchHighlightNodeIds = new Set();
      renderer.searchHighlightNodes = new Set();
      renderer.searchHighlightColor = null;
      renderer.changed?.();
    }
  }

  patchRenderer(renderer) {
    if (!renderer || this.rendererPatches.has(renderer)) {
      return;
    }

    if (typeof renderer.getHighlightNode !== "function") {
      return;
    }

    const plugin = this;
    renderer.isSearchHighlightedNode = function(node) {
      return plugin.isSearchHighlightedNode(this, node);
    };
    renderer.isSearchRelatedNode = function(node) {
      return plugin.isSearchRelatedNode(this, node);
    };

    renderer.searchHighlightNodeIds = new Set();
    renderer.searchHighlightNodes = new Set();
    renderer.searchHighlightColor = null;
    this.rendererPatches.set(renderer, {});
  }

  patchRendererElements(renderer) {
    for (const node of renderer.nodes ?? []) {
      this.patchGraphNode(node);
    }

    for (const link of renderer.links ?? []) {
      this.patchGraphLink(link);
    }
  }

  patchGraphNode(node) {
    if (!node || this.nodePatches.has(node) || typeof node.render !== "function") {
      return;
    }

    const originalRender = node.render;
    const originalInitGraphics = typeof node.initGraphics === "function" ? node.initGraphics : null;
    const originalGetDisplayText = typeof node.getDisplayText === "function" ? node.getDisplayText : null;
    const plugin = this;

    if (originalInitGraphics) {
      node.initGraphics = function(...args) {
        const result = originalInitGraphics.apply(this, args);
        plugin.drawCanvasGraphNodeShape(this);
        return result;
      };
    }

    if (originalGetDisplayText) {
      node.getDisplayText = function(...args) {
        if (this[CANVAS_NODE_LABEL_PROPERTY]) {
          return this[CANVAS_NODE_LABEL_PROPERTY];
        }
        return originalGetDisplayText.apply(this, args);
      };
    }

    node.render = function(...args) {
      const renderer = this.renderer;
      const nativeHighlight = renderer.getHighlightNode?.();
      const searchHighlightNode = nativeHighlight ? null : plugin.getNodeSearchHighlightNode(renderer, this);

      if (!searchHighlightNode) {
        return originalRender.apply(this, args);
      }

      const previousHighlightNode = renderer.highlightNode;
      renderer.highlightNode = searchHighlightNode;
      try {
        if (plugin.isSearchHighlightedNode(renderer, this)) {
          return plugin.renderWithSearchHighlightColor(renderer, () => originalRender.apply(this, args));
        }
        return originalRender.apply(this, args);
      } finally {
        renderer.highlightNode = previousHighlightNode;
      }
    };

    this.nodePatches.set(node, {
      render: originalRender,
      initGraphics: originalInitGraphics,
      getDisplayText: originalGetDisplayText
    });
  }

  patchGraphLink(link) {
    if (!link || this.linkPatches.has(link) || typeof link.render !== "function") {
      return;
    }

    const originalRender = link.render;
    const plugin = this;

    link.render = function(...args) {
      const renderer = this.renderer;
      const nativeHighlight = renderer.getHighlightNode?.();
      const highlightedNode = nativeHighlight ? null : plugin.getLinkSearchHighlightNode(renderer, this);
      const renderLink = () => plugin.renderWithCanvasGraphLinkColor(
        renderer,
        this,
        () => originalRender.apply(this, args)
      );

      if (!highlightedNode) {
        return renderLink();
      }

      const previousHighlightNode = renderer.highlightNode;
      renderer.highlightNode = highlightedNode;
      try {
        return renderLink();
      } finally {
        renderer.highlightNode = previousHighlightNode;
      }
    };

    this.linkPatches.set(link, { render: originalRender });
  }

  restoreRenderer(renderer) {
    if (!renderer) {
      return;
    }

    const rendererPatch = this.rendererPatches.get(renderer);
    if (rendererPatch) {
      delete renderer.isSearchHighlightedNode;
      delete renderer.isSearchRelatedNode;
      delete renderer.searchHighlightNodeIds;
      delete renderer.searchHighlightNodes;
      delete renderer.searchHighlightColor;
      this.rendererPatches.delete(renderer);
    }

    for (const node of renderer.nodes ?? []) {
      const nodePatch = this.nodePatches.get(node);
      if (nodePatch) {
        node.render = nodePatch.render;
        if (nodePatch.initGraphics) {
          node.initGraphics = nodePatch.initGraphics;
        }
        if (nodePatch.getDisplayText) {
          node.getDisplayText = nodePatch.getDisplayText;
        }
        this.nodePatches.delete(node);
      }
    }

    for (const link of renderer.links ?? []) {
      const linkPatch = this.linkPatches.get(link);
      if (linkPatch) {
        link.render = linkPatch.render;
        this.linkPatches.delete(link);
      }
    }
  }

  isSearchHighlightedNode(renderer, node) {
    return renderer?.searchHighlightNodes?.has(node) === true;
  }

  getFirstSearchHighlightedNode(renderer) {
    const highlights = renderer?.searchHighlightNodes;
    if (!highlights || highlights.size === 0) {
      return null;
    }

    return highlights.values().next().value ?? null;
  }

  getNodeSearchHighlightNode(renderer, node) {
    const firstHighlight = this.getFirstSearchHighlightedNode(renderer);
    if (!firstHighlight) {
      return null;
    }

    if (this.isSearchHighlightedNode(renderer, node)) {
      return node;
    }

    for (const highlighted of renderer.searchHighlightNodes ?? []) {
      if (node.forward?.hasOwnProperty(highlighted.id) || node.reverse?.hasOwnProperty(highlighted.id)) {
        return highlighted;
      }
    }

    return firstHighlight;
  }

  isSearchRelatedNode(renderer, node) {
    if (this.isSearchHighlightedNode(renderer, node)) {
      return true;
    }

    for (const highlighted of renderer?.searchHighlightNodes ?? []) {
      if (node.forward?.hasOwnProperty(highlighted.id) || node.reverse?.hasOwnProperty(highlighted.id)) {
        return true;
      }
    }

    return false;
  }

  getLinkSearchHighlightNode(renderer, link) {
    const firstHighlight = this.getFirstSearchHighlightedNode(renderer);
    if (!firstHighlight) {
      return null;
    }

    if (this.isSearchHighlightedNode(renderer, link.source)) {
      return link.source;
    }
    if (this.isSearchHighlightedNode(renderer, link.target)) {
      return link.target;
    }
    return firstHighlight;
  }

  renderWithSearchHighlightColor(renderer, renderNode) {
    const color = renderer.searchHighlightColor;
    const colors = renderer.colors;
    if (!color || !colors?.fillHighlight) {
      return renderNode();
    }

    const previousFillHighlight = colors.fillHighlight;
    colors.fillHighlight = color;
    try {
      return renderNode();
    } finally {
      colors.fillHighlight = previousFillHighlight;
    }
  }

  renderWithCanvasGraphLinkColor(renderer, link, renderLink) {
    const color = link[CANVAS_LINK_COLOR_PROPERTY];
    const colors = renderer?.colors;
    if (typeof color !== "number" || !colors?.line || !colors?.lineHighlight || !colors?.arrow) {
      return renderLink();
    }

    const previousLine = colors.line;
    const previousLineHighlight = colors.lineHighlight;
    const previousArrow = colors.arrow;
    colors.line = { ...previousLine, rgb: color };
    colors.lineHighlight = { ...previousLineHighlight, rgb: color };
    colors.arrow = { ...previousArrow, rgb: color };

    try {
      return renderLink();
    } finally {
      colors.line = previousLine;
      colors.lineHighlight = previousLineHighlight;
      colors.arrow = previousArrow;
    }
  }

  drawCanvasGraphNodeShape(node) {
    const shape = node?.[CANVAS_NODE_SHAPE_PROPERTY];
    const graphics = node?.circle;
    if (!shape || !graphics || typeof graphics.clear !== "function") {
      return;
    }

    graphics.clear();
    graphics.beginFill?.(0xffffff, 1);

    if (shape === "circle") {
      graphics.drawCircle?.(GRAPH_NODE_CENTER, GRAPH_NODE_CENTER, GRAPH_NODE_RADIUS);
    } else if (shape === "square" && typeof graphics.drawRect === "function") {
      graphics.drawRect(0, 0, GRAPH_NODE_DIAMETER, GRAPH_NODE_DIAMETER);
    } else {
      const sides = shape === "triangle" ? 3 : shape === "pentagon" ? 5 : shape === "hexagon" ? 6 : 4;
      this.drawRegularGraphPolygon(graphics, sides);
    }

    graphics.endFill?.();
  }

  drawRegularGraphPolygon(graphics, sides) {
    const startAngle = -Math.PI / 2;
    let firstX = 0;
    let firstY = 0;

    for (let index = 0; index < sides; index++) {
      const angle = startAngle + (Math.PI * 2 * index) / sides;
      const x = GRAPH_NODE_CENTER + Math.cos(angle) * GRAPH_NODE_RADIUS;
      const y = GRAPH_NODE_CENTER + Math.sin(angle) * GRAPH_NODE_RADIUS;

      if (index === 0) {
        firstX = x;
        firstY = y;
        graphics.moveTo?.(x, y);
      } else {
        graphics.lineTo?.(x, y);
      }
    }

    graphics.lineTo?.(firstX, firstY);
  }

  createSearchHighlightColor(engine) {
    return {
      a: 1,
      rgb: this.hexToRgb(this.getSearchHighlightColorHex(engine)),
      [SEARCH_HIGHLIGHT_COLOR_MARKER]: true
    };
  }

  getSearchHighlightColorHex(engine) {
    return this.normalizeHexColor(engine.options?.[SEARCH_HIGHLIGHT_COLOR_OPTION]) ?? SEARCH_HIGHLIGHT_DEFAULT_COLOR;
  }

  normalizeHexColor(value) {
    if (typeof value !== "string") {
      return null;
    }

    const color = value.trim();
    if (/^#[0-9a-f]{6}$/i.test(color)) {
      return color.toLowerCase();
    }
    if (/^[0-9a-f]{6}$/i.test(color)) {
      return `#${color.toLowerCase()}`;
    }
    return null;
  }

  hexToRgb(color) {
    return parseInt(color.slice(1), 16);
  }

  resolveCssColor(color, doc = document) {
    const hexColor = this.normalizeHexColor(color);
    if (hexColor) {
      return hexColor;
    }

    const el = doc.createElement("div");
    el.style.color = color;
    el.style.display = "none";
    doc.body.appendChild(el);

    try {
      const resolvedColor = (doc.defaultView ?? window).getComputedStyle(el).color;
      const match = resolvedColor.match(/^rgba?\(\s*(\d+)(?:,|\s+)\s*(\d+)(?:,|\s+)\s*(\d+)/);
      if (!match) {
        return null;
      }
      const rgb = (parseInt(match[1], 10) << 16) + (parseInt(match[2], 10) << 8) + parseInt(match[3], 10);
      return `#${rgb.toString(16).padStart(6, "0")}`;
    } finally {
      this.detachElement(el);
    }
  }

  refreshGraphSearch(engine) {
    if (typeof engine?.updateSearch === "function") {
      engine.updateSearch();
    } else {
      engine?.requestUpdateSearch?.run?.();
    }
  }

  getGraphEngine(view) {
    const viewType = view?.getViewType?.();
    if (viewType === GRAPH_VIEW_TYPE) {
      return view.dataEngine;
    }
    if (viewType === LOCAL_GRAPH_VIEW_TYPE) {
      return view.engine;
    }
    return null;
  }

  hasOpenGraphView() {
    let hasGraphView = false;
    this.app.workspace.iterateAllLeaves((leaf) => {
      const viewType = leaf?.view?.getViewType?.();
      if (viewType === GRAPH_VIEW_TYPE || viewType === LOCAL_GRAPH_VIEW_TYPE) {
        hasGraphView = true;
      }
    });
    return hasGraphView;
  }

  renderOpenGraphViews() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const engine = this.getGraphEngine(leaf?.view);
      engine?.render?.();
    });
  }
};

},
"./src/canvas-graph.js": function(module, exports, require) {
const { Setting, TFile } = require("obsidian");
const {
  CANVAS_LINK_COLOR_PROPERTY,
  CANVAS_NODE_LABEL_PROPERTY,
  CANVAS_NODE_SHAPE_PROPERTY
} = require("./graph-properties");

const CANVAS_LINK_MODE_OPTION = "cluddlegraphsCanvasLinkMode";
const CANVAS_LINK_COLOR_OPTION = "cluddlegraphsCanvasLinkColor";
const CANVAS_CARDS_OPTION = "cluddlegraphsCanvasCards";
const CANVAS_NODE_SHAPE_OPTIONS = {
  file: "cluddlegraphsCanvasFileNodeShape",
  text: "cluddlegraphsCanvasTextNodeShape",
  link: "cluddlegraphsCanvasLinkNodeShape",
  group: "cluddlegraphsCanvasGroupNodeShape"
};
const CANVAS_LINK_MODE_DEFAULT = "all";
const CANVAS_LINK_COLOR_DEFAULT = "#7c3aed";
const CANVAS_NODE_SHAPE_DEFAULTS = {
  file: "circle",
  text: "square",
  link: "square",
  group: "square"
};
const CANVAS_NODE_TYPES = ["file", "text", "link", "group"];
const CANVAS_SHAPES = ["circle", "triangle", "square", "pentagon", "hexagon"];
const CANVAS_GRAPH_ONLY_NODE_PREFIX = "cluddlegraphs-canvas-node";
const CANVAS_LINK_MODE_CLASS = "cluddlegraphs-canvas-link-mode";
const CANVAS_CARDS_CLASS = "cluddlegraphs-canvas-cards";
const CANVAS_LINK_COLOR_CLASS = "cluddlegraphs-canvas-link-color";
const CANVAS_NODE_SHAPE_CLASS_PREFIX = "cluddlegraphs-canvas-node-shape";
const UNRESOLVED_CANVAS_COLOR = 0x010203;

const CANVAS_LINK_MODE_LABELS = {
  all: "All links",
  hide: "Hide canvas links",
  only: "Canvas links only"
};

const CANVAS_SHAPE_LABELS = {
  circle: "Circle",
  triangle: "Triangle",
  square: "Square",
  pentagon: "Pentagon",
  hexagon: "Hexagon"
};

module.exports = class CanvasGraphController {
  constructor(plugin) {
    this.plugin = plugin;
    this.rendererPatches = new WeakMap();
    this.filterControls = new WeakMap();
    this.displayControls = new WeakMap();
    this.canvasGraphLinks = {};
    this.canvasGraphNodes = {};
    this.hydration = null;
    this.hydrated = false;
    this.needsHydration = true;
  }

  onload() {
    const requestHydration = (file) => {
      if (this.hasOpenGraphView()) {
        void this.hydrate(file instanceof TFile && file.extension === "canvas" ? file : undefined);
      } else {
        this.needsHydration = true;
      }
    };

    this.plugin.registerEvent(this.plugin.app.vault.on("create", (file) => {
      if (file instanceof TFile && file.extension === "canvas") {
        requestHydration(file);
      }
    }));
    this.plugin.registerEvent(this.plugin.app.vault.on("modify", (file) => {
      if (file instanceof TFile && file.extension === "canvas") {
        requestHydration(file);
      }
    }));
    this.plugin.registerEvent(this.plugin.app.vault.on("delete", () => requestHydration()));
    this.plugin.registerEvent(this.plugin.app.vault.on("rename", () => requestHydration()));
  }

  syncEngine(engine) {
    this.initializeOptions(engine);
    this.addFilterControls(engine);
    this.addDisplayControls(engine);
    this.patchRenderer(engine);

    if (!this.hydrated || this.needsHydration) {
      void this.hydrate();
    }
  }

  restoreEngine(engine) {
    const renderer = engine?.renderer;
    const patch = renderer ? this.rendererPatches.get(renderer) : null;
    if (patch) {
      renderer.setData = patch.setData;
      this.rendererPatches.delete(renderer);
    }

    this.removeControls(engine);
    this.clearRendererMetadata(renderer);
  }

  initializeOptions(engine) {
    const savedOptions = this.plugin.getSavedGraphOptions(engine) ?? {};
    engine.options[CANVAS_LINK_MODE_OPTION] =
      this.parseLinkMode(engine.options?.[CANVAS_LINK_MODE_OPTION])
      ?? this.parseLinkMode(savedOptions[CANVAS_LINK_MODE_OPTION])
      ?? CANVAS_LINK_MODE_DEFAULT;
    engine.options[CANVAS_LINK_COLOR_OPTION] =
      this.plugin.normalizeHexColor(engine.options?.[CANVAS_LINK_COLOR_OPTION])
      ?? this.plugin.normalizeHexColor(savedOptions[CANVAS_LINK_COLOR_OPTION])
      ?? this.getDefaultCanvasLinkColor(engine);
    engine.options[CANVAS_CARDS_OPTION] =
      typeof engine.options?.[CANVAS_CARDS_OPTION] === "boolean"
        ? engine.options[CANVAS_CARDS_OPTION]
        : savedOptions[CANVAS_CARDS_OPTION] !== false;

    for (const type of CANVAS_NODE_TYPES) {
      const option = CANVAS_NODE_SHAPE_OPTIONS[type];
      engine.options[option] =
        this.parseShape(engine.options?.[option])
        ?? this.parseShape(savedOptions[option])
        ?? CANVAS_NODE_SHAPE_DEFAULTS[type];
    }
  }

  addFilterControls(engine) {
    const filterOptions = engine.filterOptions;
    const childrenEl = filterOptions?.childrenEl;
    if (!childrenEl) {
      return;
    }

    const trackedControls = this.filterControls.get(engine);
    if (trackedControls?.every((setting) => setting.settingEl.parentElement === childrenEl)) {
      return;
    }

    this.removeExistingControls(childrenEl, [CANVAS_LINK_MODE_CLASS, CANVAS_CARDS_CLASS], trackedControls);

    const linkModeSetting = new Setting(childrenEl)
      .setName("Canvas links")
      .setDesc("Show, hide, or isolate links drawn between items inside canvases.")
      .setClass(CANVAS_LINK_MODE_CLASS)
      .addDropdown((dropdown) => {
        for (const [value, label] of Object.entries(CANVAS_LINK_MODE_LABELS)) {
          dropdown.addOption(value, label);
        }

        dropdown
          .setValue(this.getLinkMode(engine))
          .onChange((value) => {
            engine.options[CANVAS_LINK_MODE_OPTION] = this.parseLinkMode(value) ?? CANVAS_LINK_MODE_DEFAULT;
            engine.render?.();
            engine.onOptionsChange?.();
          });

        filterOptions.optionListeners[CANVAS_LINK_MODE_OPTION] = (value) => {
          const mode = this.parseLinkMode(value);
          if (mode) {
            engine.options[CANVAS_LINK_MODE_OPTION] = mode;
            dropdown.setValue(mode);
            engine.render?.();
          }
          return this.getLinkMode(engine);
        };
      });

    const cardsSetting = new Setting(childrenEl)
      .setName("Canvas cards")
      .setDesc("Show graph-only nodes for Canvas text, link, and group cards.")
      .setClass("mod-toggle")
      .setClass(CANVAS_CARDS_CLASS)
      .addToggle((toggle) => {
        toggle
          .setValue(this.shouldShowCards(engine))
          .onChange((enabled) => {
            engine.options[CANVAS_CARDS_OPTION] = enabled;
            engine.render?.();
            engine.onOptionsChange?.();
          });

        filterOptions.optionListeners[CANVAS_CARDS_OPTION] = (value) => {
          if (typeof value === "boolean") {
            engine.options[CANVAS_CARDS_OPTION] = value;
            toggle.setValue(value);
            engine.render?.();
          }
          return this.shouldShowCards(engine);
        };
      });

    this.filterControls.set(engine, [linkModeSetting, cardsSetting]);
  }

  addDisplayControls(engine) {
    const displayOptions = engine.displayOptions;
    const childrenEl = displayOptions?.childrenEl;
    if (!childrenEl) {
      return;
    }

    const trackedControls = this.displayControls.get(engine);
    if (trackedControls?.every((setting) => setting.settingEl.parentElement === childrenEl)) {
      return;
    }

    this.removeExistingControls(
      childrenEl,
      [CANVAS_LINK_COLOR_CLASS, ...CANVAS_NODE_TYPES.map((type) => `${CANVAS_NODE_SHAPE_CLASS_PREFIX}-${type}`)],
      trackedControls
    );

    const colorSetting = new Setting(childrenEl)
      .setName("Canvas links")
      .setDesc("Fallback color for Canvas graph links without a Canvas edge color.")
      .setClass(CANVAS_LINK_COLOR_CLASS)
      .addColorPicker((colorPicker) => {
        colorPicker
          .setValue(this.getLinkColor(engine))
          .onChange((value) => {
            const color = this.plugin.normalizeHexColor(value);
            if (!color) {
              return;
            }

            engine.options[CANVAS_LINK_COLOR_OPTION] = color;
            engine.render?.();
            engine.onOptionsChange?.();
          });

        displayOptions.optionListeners[CANVAS_LINK_COLOR_OPTION] = (value) => {
          const color = this.plugin.normalizeHexColor(value);
          if (color) {
            engine.options[CANVAS_LINK_COLOR_OPTION] = color;
            colorPicker.setValue(color);
            engine.render?.();
          }
          return this.getLinkColor(engine);
        };
      });

    const shapeSettings = CANVAS_NODE_TYPES.map((type) => this.addShapeControl(engine, displayOptions, childrenEl, type));
    this.displayControls.set(engine, [colorSetting, ...shapeSettings]);
  }

  addShapeControl(engine, displayOptions, childrenEl, type) {
    const option = CANVAS_NODE_SHAPE_OPTIONS[type];
    const setting = new Setting(childrenEl)
      .setName(`Canvas ${type} nodes`)
      .setDesc("Shape used for this Canvas item type in graph views.")
      .setClass(`${CANVAS_NODE_SHAPE_CLASS_PREFIX}-${type}`)
      .addDropdown((dropdown) => {
        for (const [value, label] of Object.entries(CANVAS_SHAPE_LABELS)) {
          dropdown.addOption(value, label);
        }

        dropdown
          .setValue(this.getNodeShape(engine, type))
          .onChange((value) => {
            engine.options[option] = this.parseShape(value) ?? CANVAS_NODE_SHAPE_DEFAULTS[type];
            engine.render?.();
            engine.onOptionsChange?.();
          });

        displayOptions.optionListeners[option] = (value) => {
          const shape = this.parseShape(value);
          if (shape) {
            engine.options[option] = shape;
            dropdown.setValue(shape);
            engine.render?.();
          }
          return this.getNodeShape(engine, type);
        };
      });

    return setting;
  }

  removeControls(engine) {
    for (const setting of this.filterControls.get(engine) ?? []) {
      this.plugin.detachElement(setting.settingEl);
    }
    for (const setting of this.displayControls.get(engine) ?? []) {
      this.plugin.detachElement(setting.settingEl);
    }
    this.filterControls.delete(engine);
    this.displayControls.delete(engine);

    delete engine?.filterOptions?.optionListeners?.[CANVAS_LINK_MODE_OPTION];
    delete engine?.filterOptions?.optionListeners?.[CANVAS_CARDS_OPTION];
    delete engine?.displayOptions?.optionListeners?.[CANVAS_LINK_COLOR_OPTION];
    for (const option of Object.values(CANVAS_NODE_SHAPE_OPTIONS)) {
      delete engine?.displayOptions?.optionListeners?.[option];
    }
  }

  removeExistingControls(childrenEl, controlClasses, trackedControls) {
    const trackedEls = new Set((trackedControls ?? []).map((setting) => setting.settingEl));
    for (const controlClass of controlClasses) {
      for (const existingEl of childrenEl.querySelectorAll?.(`.${controlClass}`) ?? []) {
        if (!trackedEls.has(existingEl)) {
          this.plugin.detachElement(existingEl);
        }
      }
    }
  }

  patchRenderer(engine) {
    const renderer = engine?.renderer;
    if (!renderer || this.rendererPatches.has(renderer) || typeof renderer.setData !== "function") {
      return;
    }

    const originalSetData = renderer.setData;
    const controller = this;
    renderer.setData = function(data) {
      const canvasLinks = controller.applyCanvasLinksToGraphData(data, engine);
      const result = originalSetData.call(this, data);
      controller.syncRenderer(engine, canvasLinks);
      return result;
    };

    this.rendererPatches.set(renderer, { setData: originalSetData });
  }

  applyCanvasLinksToGraphData(data, engine) {
    const nativeLinks = this.getGraphLinkKeys(data);
    const canvasLinks = this.getCanvasGraphLinks(data, engine);
    const mode = this.getLinkMode(engine);

    if (mode !== "hide") {
      this.addCanvasGraphLinks(data, engine, canvasLinks);
    }
    if (mode === "hide") {
      this.removeCanvasGraphLinks(data, canvasLinks, nativeLinks);
    } else if (mode === "only") {
      this.keepOnlyCanvasGraphLinks(data, canvasLinks);
    }

    if (mode !== "all" && !engine.options.showOrphans) {
      this.removeOrphanNodes(data);
    }

    data.numLinks = this.getGraphLinkKeys(data).size;
    return canvasLinks;
  }

  syncRenderer(engine, canvasLinks) {
    const renderer = engine?.renderer;
    if (!renderer) {
      return;
    }

    const defaultColor = this.plugin.hexToRgb(this.getLinkColor(engine));
    const doc = renderer.containerEl?.ownerDocument ?? renderer.containerEl?.doc ?? document;

    for (const node of renderer.nodes ?? []) {
      this.syncNode(engine, node);
      this.plugin.patchGraphNode(node);
      this.plugin.drawCanvasGraphNodeShape(node);
    }

    for (const link of renderer.links ?? []) {
      const canvasLink = canvasLinks[this.getLinkKey(link.source?.id, link.target?.id)];
      if (canvasLink) {
        link[CANVAS_LINK_COLOR_PROPERTY] = this.getRenderedLinkColor(canvasLink, defaultColor, doc);
      } else {
        delete link[CANVAS_LINK_COLOR_PROPERTY];
      }
      this.plugin.patchGraphLink(link);
    }

    renderer.changed?.();
  }

  syncNode(engine, node) {
    const metadata = this.canvasGraphNodes[node?.id];
    if (!metadata || (metadata.type !== "file" && !this.shouldShowCards(engine))) {
      if (node?.[CANVAS_NODE_SHAPE_PROPERTY]) {
        delete node[CANVAS_NODE_LABEL_PROPERTY];
        node[CANVAS_NODE_SHAPE_PROPERTY] = "circle";
      }
      return;
    }

    node[CANVAS_NODE_LABEL_PROPERTY] = metadata.type === "file" ? undefined : metadata.label;
    node[CANVAS_NODE_SHAPE_PROPERTY] = this.getNodeShape(engine, metadata.type);
    if (node.text && metadata.type !== "file") {
      node.text.text = metadata.label;
    }
    node.fontDirty = true;
  }

  clearRendererMetadata(renderer) {
    for (const node of renderer?.nodes ?? []) {
      delete node[CANVAS_NODE_LABEL_PROPERTY];
      delete node[CANVAS_NODE_SHAPE_PROPERTY];
    }
    for (const link of renderer?.links ?? []) {
      delete link[CANVAS_LINK_COLOR_PROPERTY];
    }
    renderer?.changed?.();
  }

  async hydrate(file) {
    if (this.hydration) {
      this.needsHydration = true;
      return this.hydration;
    }

    this.needsHydration = false;
    this.hydration = this.loadCanvasGraphData(file)
      .finally(async () => {
        this.hydration = null;
        if (!this.needsHydration) {
          return;
        }

        this.needsHydration = false;
        await this.hydrate();
      });

    return this.hydration;
  }

  async loadCanvasGraphData(file) {
    const links = file ? { ...this.canvasGraphLinks } : {};
    const nodes = file ? this.removeNodesForCanvas({ ...this.canvasGraphNodes }, file.path) : {};
    if (file) {
      delete links[file.path];
    }

    const canvasFiles = file
      ? [file]
      : this.plugin.app.vault.getFiles().filter((vaultFile) => vaultFile.extension === "canvas");

    for (const canvasFile of canvasFiles) {
      try {
        const source = await this.plugin.app.vault.cachedRead(canvasFile);
        const graphData = this.parseCanvasGraphData(canvasFile.path, source);
        links[canvasFile.path] = graphData.links;
        Object.assign(nodes, graphData.nodes);
      } catch (error) {
        console.error("Cluddle Graphs: failed to read canvas graph data", canvasFile.path, error);
      }
    }

    this.canvasGraphLinks = links;
    this.canvasGraphNodes = nodes;
    this.hydrated = true;
    this.renderOpenGraphViews();
  }

  parseCanvasGraphData(canvasPath, source) {
    let data;
    try {
      data = JSON.parse(source);
    } catch {
      return { links: {}, nodes: {} };
    }

    const graphNodes = new Map();
    for (const node of data.nodes ?? []) {
      const graphNode = this.toCanvasGraphNode(canvasPath, node);
      if (graphNode) {
        graphNodes.set(node.id, graphNode);
      }
    }

    const links = {};
    const nodes = {};
    for (const edge of data.edges ?? []) {
      const sourceNode = graphNodes.get(edge.fromNode);
      const targetNode = graphNodes.get(edge.toNode);
      if (!sourceNode || !targetNode) {
        continue;
      }

      nodes[sourceNode.id] = this.toGraphNodeMetadata(sourceNode);
      nodes[targetNode.id] = this.toGraphNodeMetadata(targetNode);
      const sourceLinks = links[sourceNode.id] ??= {};
      const resolvedLink = sourceLinks[targetNode.id] ??= { count: 0, colors: [] };
      resolvedLink.count++;
      if (edge.color && !resolvedLink.colors.includes(edge.color)) {
        resolvedLink.colors.push(edge.color);
      }
    }

    return { links, nodes };
  }

  toCanvasGraphNode(canvasPath, node) {
    if (!node?.id || !node.type) {
      return null;
    }

    if (node.type === "file") {
      const resolvedFile = node.file
        ? this.plugin.app.metadataCache.getFirstLinkpathDest(node.file, canvasPath)
        : null;
      if (!resolvedFile) {
        return null;
      }

      return {
        id: resolvedFile.path,
        canvasPath,
        label: resolvedFile.basename,
        type: "file"
      };
    }

    if (node.type !== "text" && node.type !== "link" && node.type !== "group") {
      return null;
    }

    return {
      id: this.getGraphOnlyNodeId(canvasPath, node.id),
      canvasPath,
      label: this.getGraphOnlyNodeLabel(node),
      type: node.type
    };
  }

  toGraphNodeMetadata(node) {
    return {
      canvasPath: node.canvasPath,
      label: node.label,
      type: node.type
    };
  }

  getGraphOnlyNodeLabel(node) {
    if (node.type === "text") {
      return this.cleanLabel(node.text) || "Text card";
    }
    if (node.type === "link") {
      return this.cleanLabel(this.getUrlLabel(node.url)) || "Link card";
    }
    return this.cleanLabel(node.label) || "Group";
  }

  cleanLabel(label) {
    return String(label ?? "")
      .replace(/!\[\[[^\]]+\]\]/g, "")
      .replace(/\[\[([^\]|]+)(?:\|([^\]]+))?\]\]/g, (_match, link, alias) => alias ?? link)
      .replace(/[*_`>#-]/g, "")
      .replace(/\s+/g, " ")
      .trim()
      .slice(0, 80);
  }

  getUrlLabel(url) {
    try {
      return new URL(url).hostname || url;
    } catch {
      return url;
    }
  }

  getGraphOnlyNodeId(canvasPath, nodeId) {
    return `${canvasPath}#${CANVAS_GRAPH_ONLY_NODE_PREFIX}-${nodeId}`;
  }

  removeNodesForCanvas(nodes, canvasPath) {
    for (const [nodeId, node] of Object.entries(nodes)) {
      if (node.canvasPath === canvasPath) {
        delete nodes[nodeId];
      }
    }
    return nodes;
  }

  getCanvasGraphLinks(data, engine) {
    const links = {};
    for (const canvasLinks of Object.values(this.canvasGraphLinks)) {
      for (const [sourcePath, targets] of Object.entries(canvasLinks)) {
        for (const [targetPath, link] of Object.entries(targets)) {
          if (sourcePath === targetPath) {
            continue;
          }
          if (!this.shouldIncludeCanvasGraphLink(data, engine, sourcePath, targetPath)) {
            continue;
          }

          const key = this.getLinkKey(sourcePath, targetPath);
          const existingLink = links[key] ?? { sourcePath, targetPath, count: 0, colors: [] };
          existingLink.count += link.count;
          for (const color of link.colors) {
            if (!existingLink.colors.includes(color)) {
              existingLink.colors.push(color);
            }
          }
          links[key] = existingLink;
        }
      }
    }
    return links;
  }

  shouldIncludeCanvasGraphLink(data, engine, sourcePath, targetPath) {
    if (!this.shouldAllowGraphNode(engine, sourcePath) || !this.shouldAllowGraphNode(engine, targetPath)) {
      return false;
    }

    const localFile = engine.options?.localFile;
    if (!localFile) {
      return true;
    }

    if (sourcePath === localFile) {
      return engine.options.localForelinks !== false;
    }
    if (targetPath === localFile) {
      return engine.options.localBacklinks !== false;
    }

    return engine.options.localInterlinks === true && !!data.nodes[sourcePath] && !!data.nodes[targetPath];
  }

  shouldAllowGraphNode(engine, path) {
    if (this.isGraphOnlyNode(path)) {
      return this.shouldShowCards(engine);
    }
    if (!engine.options?.showAttachments && this.isAttachmentPath(path)) {
      return false;
    }
    if (typeof this.plugin.app.metadataCache.isUserIgnored === "function"
      && this.plugin.app.metadataCache.isUserIgnored(path)) {
      return false;
    }
    if (engine.hasFilter) {
      return !!engine.fileFilter?.[path];
    }
    return true;
  }

  addCanvasGraphLinks(data, engine, canvasLinks) {
    for (const link of Object.values(canvasLinks)) {
      this.ensureGraphNode(data, engine, link.sourcePath);
      this.ensureGraphNode(data, engine, link.targetPath);

      const sourceNode = data.nodes[link.sourcePath];
      if (!sourceNode || !data.nodes[link.targetPath]) {
        continue;
      }

      sourceNode.links ??= {};
      sourceNode.links[link.targetPath] = true;
    }
  }

  ensureGraphNode(data, engine, path) {
    if (data.nodes[path] || !this.shouldAllowGraphNode(engine, path)) {
      return;
    }

    const metadata = this.canvasGraphNodes[path];
    if (!metadata && !(this.plugin.app.vault.getAbstractFileByPath(path) instanceof TFile)) {
      return;
    }

    data.nodes[path] = {
      type: metadata && metadata.type !== "file" ? "cluddlegraphs-canvas-card" : this.isAttachmentPath(path) ? "attachment" : "",
      links: {}
    };
  }

  removeCanvasGraphLinks(data, canvasLinks, nativeLinks) {
    for (const link of Object.values(canvasLinks)) {
      if (!nativeLinks.has(this.getLinkKey(link.sourcePath, link.targetPath))) {
        delete data.nodes[link.sourcePath]?.links?.[link.targetPath];
      }
    }
  }

  keepOnlyCanvasGraphLinks(data, canvasLinks) {
    const canvasLinkKeys = new Set(Object.keys(canvasLinks));
    for (const [sourcePath, node] of Object.entries(data.nodes)) {
      for (const targetPath of Object.keys(node.links ?? {})) {
        if (!canvasLinkKeys.has(this.getLinkKey(sourcePath, targetPath))) {
          delete node.links?.[targetPath];
        }
      }
    }
  }

  removeOrphanNodes(data) {
    const hasIncomingLink = {};
    for (const [sourcePath, node] of Object.entries(data.nodes)) {
      for (const targetPath of Object.keys(node.links ?? {})) {
        if (sourcePath !== targetPath && data.nodes[targetPath]) {
          hasIncomingLink[targetPath] = true;
        }
      }
    }

    for (const [sourcePath, node] of Object.entries(data.nodes)) {
      const hasOutgoingLink = Object.keys(node.links ?? {})
        .some((targetPath) => sourcePath !== targetPath && !!data.nodes[targetPath]);
      if (!hasOutgoingLink && !hasIncomingLink[sourcePath]) {
        delete data.nodes[sourcePath];
      }
    }
  }

  getGraphLinkKeys(data) {
    const links = new Set();
    for (const [sourcePath, node] of Object.entries(data.nodes ?? {})) {
      for (const targetPath of Object.keys(node.links ?? {})) {
        links.add(this.getLinkKey(sourcePath, targetPath));
      }
    }
    return links;
  }

  getRenderedLinkColor(link, defaultColor, doc) {
    for (const canvasColor of link.colors) {
      const resolvedColor = this.resolveCanvasColor(canvasColor, doc);
      if (resolvedColor !== null) {
        return resolvedColor;
      }
    }
    return defaultColor;
  }

  resolveCanvasColor(color, doc) {
    const normalizedColor = this.plugin.normalizeHexColor(color);
    if (normalizedColor) {
      return this.plugin.hexToRgb(normalizedColor);
    }
    if (!/^\d+$/.test(String(color))) {
      return null;
    }

    const el = doc.createElement("div");
    el.classList.add(`mod-canvas-color-${color}`);
    el.style.color = "rgb(var(--canvas-color, 1, 2, 3))";
    el.style.display = "none";
    doc.body.appendChild(el);

    try {
      const resolvedColor = this.parseRgbColor((doc.defaultView ?? window).getComputedStyle(el).color);
      return resolvedColor === UNRESOLVED_CANVAS_COLOR ? null : resolvedColor;
    } finally {
      this.plugin.detachElement(el);
    }
  }

  parseRgbColor(color) {
    const match = color.match(/^rgba?\(\s*(\d+)(?:,|\s+)\s*(\d+)(?:,|\s+)\s*(\d+)/);
    if (!match) {
      return null;
    }
    return (parseInt(match[1], 10) << 16) + (parseInt(match[2], 10) << 8) + parseInt(match[3], 10);
  }

  getLinkMode(engine) {
    return this.parseLinkMode(engine.options?.[CANVAS_LINK_MODE_OPTION]) ?? CANVAS_LINK_MODE_DEFAULT;
  }

  parseLinkMode(value) {
    return value === "all" || value === "hide" || value === "only" ? value : null;
  }

  shouldShowCards(engine) {
    return engine.options?.[CANVAS_CARDS_OPTION] !== false;
  }

  getLinkColor(engine) {
    return this.plugin.normalizeHexColor(engine.options?.[CANVAS_LINK_COLOR_OPTION])
      ?? this.getDefaultCanvasLinkColor(engine);
  }

  getDefaultCanvasLinkColor(engine) {
    return this.plugin.resolveCssColor?.("var(--color-accent)", engine.renderer?.containerEl?.ownerDocument ?? document)
      ?? CANVAS_LINK_COLOR_DEFAULT;
  }

  getNodeShape(engine, type) {
    return this.parseShape(engine.options?.[CANVAS_NODE_SHAPE_OPTIONS[type]]) ?? CANVAS_NODE_SHAPE_DEFAULTS[type];
  }

  parseShape(value) {
    return CANVAS_SHAPES.includes(value) ? value : null;
  }

  isGraphOnlyNode(path) {
    return this.canvasGraphNodes[path]?.type !== undefined && this.canvasGraphNodes[path].type !== "file";
  }

  isAttachmentPath(path) {
    const extension = String(path).split(".").pop()?.toLowerCase();
    return extension !== "md";
  }

  getLinkKey(sourcePath, targetPath) {
    return `${sourcePath}\0${targetPath}`;
  }

  hasOpenGraphView() {
    return this.plugin.hasOpenGraphView();
  }

  renderOpenGraphViews() {
    this.plugin.renderOpenGraphViews();
  }
};

},
"./src/graph-properties.js": function(module, exports, require) {
module.exports = {
  CANVAS_LINK_COLOR_PROPERTY: "__cluddlegraphsCanvasLinkColor",
  CANVAS_NODE_LABEL_PROPERTY: "__cluddlegraphsCanvasNodeLabel",
  CANVAS_NODE_SHAPE_PROPERTY: "__cluddlegraphsCanvasNodeShape"
};

}
  };
  const __cache = {};

  function __resolve(request, parentId) {
    if (!request.startsWith(".")) {
      return request;
    }

    const parentParts = parentId.split("/");
    parentParts.pop();
    const parts = request.split("/");
    for (const part of parts) {
      if (!part || part === ".") {
        continue;
      }
      if (part === "..") {
        parentParts.pop();
      } else {
        parentParts.push(part);
      }
    }

    const resolved = parentParts.join("/");
    if (__modules[resolved]) {
      return resolved;
    }
    if (__modules[resolved + ".js"]) {
      return resolved + ".js";
    }

    return request;
  }

  function __require(request, parentId) {
    const moduleId = __resolve(request, parentId);
    if (!moduleId.startsWith(".")) {
      return require(moduleId);
    }
    if (__cache[moduleId]) {
      return __cache[moduleId].exports;
    }

    const factory = __modules[moduleId];
    if (!factory) {
      throw new Error("Bundled module not found: " + moduleId);
    }

    const module = { exports: {} };
    __cache[moduleId] = module;
    factory(module, module.exports, (id) => __require(id, moduleId));
    return module.exports;
  }

  module.exports = __require("./src/main.js", "");
})();
