#!/usr/bin/env node

const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const entry = "./src/main.js";
const modules = new Map();

function normalizeModuleId(id) {
  return `./${path.relative(rootDir, id).replace(/\\/g, "/")}`;
}

function resolveLocalModule(request, parentId) {
  if (!request.startsWith(".")) {
    return null;
  }

  const parentDir = path.dirname(path.resolve(rootDir, parentId));
  const base = path.resolve(parentDir, request);
  for (const candidate of [base, `${base}.js`, path.join(base, "index.js")]) {
    if (fs.existsSync(candidate) && fs.statSync(candidate).isFile()) {
      return normalizeModuleId(candidate);
    }
  }

  throw new Error(`Cannot resolve ${request} from ${parentId}`);
}

function collectModule(moduleId) {
  if (modules.has(moduleId)) {
    return;
  }

  const filename = path.resolve(rootDir, moduleId);
  const source = fs.readFileSync(filename, "utf8");
  modules.set(moduleId, source);

  const requirePattern = /require\(\s*["']([^"']+)["']\s*\)/g;
  for (const match of source.matchAll(requirePattern)) {
    const resolved = resolveLocalModule(match[1], moduleId);
    if (resolved) {
      collectModule(resolved);
    }
  }
}

function toModuleSource([moduleId, source]) {
  return `${JSON.stringify(moduleId)}: function(module, exports, require) {\n${source}\n}`;
}

function build() {
  modules.clear();
  collectModule(entry);

  const output = `// Generated by scripts/build.js from src/. Do not edit this file directly.
(function() {
  const __modules = {
${Array.from(modules.entries()).map(toModuleSource).join(",\n")}
  };
  const __cache = {};

  function __resolve(request, parentId) {
    if (!request.startsWith(".")) {
      return request;
    }

    const parentParts = parentId.split("/");
    parentParts.pop();
    const parts = request.split("/");
    for (const part of parts) {
      if (!part || part === ".") {
        continue;
      }
      if (part === "..") {
        parentParts.pop();
      } else {
        parentParts.push(part);
      }
    }

    const resolved = parentParts.join("/");
    if (__modules[resolved]) {
      return resolved;
    }
    if (__modules[resolved + ".js"]) {
      return resolved + ".js";
    }

    return request;
  }

  function __require(request, parentId) {
    const moduleId = __resolve(request, parentId);
    if (!moduleId.startsWith(".")) {
      return require(moduleId);
    }
    if (__cache[moduleId]) {
      return __cache[moduleId].exports;
    }

    const factory = __modules[moduleId];
    if (!factory) {
      throw new Error("Bundled module not found: " + moduleId);
    }

    const module = { exports: {} };
    __cache[moduleId] = module;
    factory(module, module.exports, (id) => __require(id, moduleId));
    return module.exports;
  }

  module.exports = __require(${JSON.stringify(entry)}, "");
})();
`;

  fs.writeFileSync(path.resolve(rootDir, "main.js"), output, "utf8");
}

build();
